### ISSUE TITLE
Filtre sur les HostGroup non fonctionnel

### ISSUE THREAD

**Issue by bmareau** [Centreon-Widgets/centreon-widget-live-top10-cpu-usage#4]
Bonjour,

Le filtre par HostGroup name n'est pas fonctionnel dans la version 1.1.0 du Widget.
Alors que ça fonctionne dans la version 1.0.0

Cdlt

**Comment by lpinsivy** [comment]
Fixed by e42122cfbd89447f1579d7a1f8497075a4ca6774
